from time import sleep, time
from turtle import title



print('After a long flight, you finally arrive to the island of "Python" where you planned a vacation for you and two of your friends after a long week of work.')
sleep(5)
protag_name= input('Your male friend calls you over by your name, which is... (enter first name) ')
sleep(2)
print(f'"Get over here, {protag_name.title()}, our stuff has arrived!"')
sleep(3)
print()
m_friend=input('As you approach, he hands you your navy blue bag and takes his own red bag with a sticker stating his name in a graffiti font. The sticker reads: (enter male friend\'s name) ')
sleep(2)
print(f'"The whole airport doesn\'t need to hear you, {m_friend.title()}, you could have just waved."')
sleep(3)
f_friend=input('"You two are always bickering, you know that?" Your other friend said as she arrived. You\'ve been friends for awhile, so how could you forget her name was... (enter female friend\'s name) ')
sleep(2)
print()
print(f'"Here\'s your bag." {m_friend.title()} said as he handed {f_friend.title()} her sea green bag. "Where\'d you walk off to anyway?"')
sleep(3)
print('"I grabbed a pamphlet from over there" she said, pointing at the magazine rack by the doors. "Now we can see all of the different tourist traps!"')
sleep(3)
print()
print('You all glanced over the pamphlet, examining your options.')
sleep(2)
print(f'"Let\'s go to \'Ian\'s taste of Italy,\' I\'m starving!" {m_friend.title()} said, his mouth salivating.')
sleep(3)
print(f'"...or we could go to the hotel and get food there. It IS getting late you know." {f_friend.title()} stated, taking note that this island isn\'t exactly safe.')
sleep(3)
choice1=input(f'"I don\'t want to eat hotel food! why don\'t you pick, {protag_name.title()}, are we going to the (1)hotel or the (2)restaurant?"(Ex: 1) ')
sleep(2)
print()

while choice1!=('1') and choice1!=('2'):
    print('You should decide before they get impatient.')
    choice1=input('Should you go to the (1)hotel or the (2)restaurant? ')
    sleep(2)
    print()
if choice1=='1':
    print(f'"Sorry, {m_friend.title()}, she\'s got a point" you say.')
    sleep(2)
    print('"C\'mon, dude, Italy was calling out to me..."')
    sleep(2)
    print(f'"It\'s not that we don\'t want to" the opposing side said in sync, "It\'s dangerous here, and we shouldn\'t be out for long" {protag_name.title()} finished.')
    sleep(4)
    print(f'"Why do all paradises have to be riddled with danger..." {m_friend.title()} said in defeat')
    print()
elif choice1=='2':
    print('"The restaurant sounds good" you say.')
    sleep(2)
    print(f'"Aw sweet!" {m_friend.title()} said as he dashed out the door.')
    sleep(2)
    print()
    print('As you all arrived at the restaurant, a finely dressed man with a scruffy beard was seen waiting at the entrance.')
    sleep(4)
    print(f'"We are all booked up for tonight, folks, now scram" the man said as he lit a cigarette, smoking from whatever stress must have been going on inside.')
    sleep(4)
    print(f'After a glance inside, you could see a child\'s birthday party with no less than 15 other children, and many adults who were presumably their respective parents.')
    sleep(4)
    print()
    print(f'"What the hell, man?! Those kids just get the entire place to themselves?!" {m_friend.title()} protested.')
    sleep(4)
    print(f'"Let\'s just go, {m_friend.title()}" {f_friend.title()} said pulling him by his arm. "We\'ll just go to the hotel and eat there.')
    sleep(4)
    print('"Fine." He replied, flipping the gentleman off as they walked away.')
    print()
    gentleman='offended'

sleep(3)
print(f'As you all arrived at the hotel, you got our room key and went into our room. You all unpacked our things as {m_friend.title()} flopped onto his bed in disappointment.')
sleep(3)
print(f'{m_friend.title()} fell asleep immediately, and you and {f_friend.title()} gradually fell asleep.')
sleep(5)
print()
print('*Crash!*')
sleep(2)
print()
print('The sound of something smashing into a million pieces woke you all up at around midnight')
sleep(3)
print()
print(f'"What the hell was that?!" {m_friend.title()} said, his heart racing. "I was having the best dream, too..."')
sleep(3)
print('"I need to find whoever did that and make them pay for stealing me away from it!" he exclaimed.')
sleep(3)
print(f'"Calm down" snaps {f_friend.title()}, being quite frieghtened herself. "We don\'t even know what it was; it could be some wild animal or something. We definitely should NOT go out there."')
sleep(4)
print()
choice2=input('As your friends argue, you figure it\'s a good time to be a leader. You have to decide whether you (1)check it out or (2)stay put. ')
sleep(3)
print()
while choice2!=('1') and choice2!=('2'):
    print('Your friends bicker while you try to decide.')
    choice2=input('Should you (1)check it out or (2)stay put? ')
    sleep(2)
    print()
# Fill in the Elif section

if choice2=="1":
    print('"Come on, it might be worth checking out."')
    sleep(3)
    print(f'"At least YOU understand, {protag_name.title()}, unlike HER."')
    sleep(2)
    print()
    print(f'{f_friend.title()} rolls her eyes as you all make your way out the door and into the hallway.')
    sleep(4)
    print('As you peer down the hall, you see an abnormally shaped creature\'s shadow lingering above the body of another guest.')
    sleep(4)
    print()
    print('You signal your freightened friends to stay quiet, Even though you yourself wanted to scream.')
    sleep(3)
    print()
    choice3_a=input('It was too late to go back into the room, as the door closing would make sound. You must decide to (1)go back in anyway or to (2)try to sneak out the back door. ')
    sleep(3)
    print()
    while choice3_a!=('1') and choice3_a!=('2'):
        print('It\'s scary, but you have to decide.')
        choice3_a=input('Should you (1)go back in or (2)try to sneak out the back? ')
        sleep(2)
        print()
    # Fill in Elif here

    if choice3_a=='1':
        print('You point back into the room and with some hesitation, you all make your way back in.')
        sleep(3)
        print('You slowly close the door and when it shuts, it makes a clicking sound.')
        sleep(2)
        print()
        print('You hear the beast roar and begin approaching your door with large and heavy steps')
        sleep(3)
        print()
        choice4_a=input('Should you signal to (1)hide or to (2)try and get out through the window? ')
        sleep(3)
        print()
        while choice4_a!='1' and choice4_a!='2':
            print('You don\'t have the time to think about this!')
            choicey4_a=input('Should you (1)hide or (2)try to get out the window?!')
            sleep(3)
            print()
        # Fill in Elif here

        if choice4_a=='1':
            print('You signal to hide and to only come out when you do as you sneak toward the towel closet in the bathroom.')
            sleep(3)
            print('You do not know where your friends hid, but you can only hope for the best.')
            sleep(3)
            print()
            print('You hear the doorknob jiggle a bit, and then suddenly the door blasted open!')
            sleep(3)
            print('You steady your breathing as you listen to the beast walk around with slow and hevy breaths as if concentrating.')
            sleep(4)
            print()
            print('You hear the movement get quieter and eventually silent.')
            sleep(2)
            print()
            choice5_a=input('You don\'t know if it\'s a trap or not, so should you (1)come out or (2)stay put a little longer')
            sleep(2)
            print()
            while choice5_a!='1' and choice5_a!='2':
                print('If you\'re going to stall, you ought to just stay put.')
                choice5_a=input('Should you (1)come out or (2)stay put?')
                sleep(3)
                print()
            # Fill in Elif here

            if choice5_a=='1':
                print('You slowly draw the curtain back and step out. As you look to the left where the entrance is, you see dark beady eyes looking back at you.')
                sleep(3)
                print()
                print('You stand there frozen, hoping it only senses movement. You\'re not so fortunate.')
                sleep(3)
                print()
                print('It begins to tear at you. Blood spilling, insides flying. The beast was doing this all without making a sound. Without you making a sound. Then there was nothing.')
                end=1
            elif choice5_a=='2':
                print('You choose to stay still.')
                sleep(5)
                print('10 minutes pass, and you start to hear movement.')
                sleep(2)
                print('You hear a grunt of disappointment, and large footsteps in the distance.')
                sleep(2)
                print('You try to wait a few more minutes, but you fall asleep within the comfort of the towels.')
                sleep(3)
                print('Morning arises, and you hear loud violent knocking where your door used to be.')
                sleep(3)
                print('"Is everyone in here okay?!" The man\'s voice was rough, and stern. His voice was worried, but on guard for sure.')
                





if end==1:
    print()
    sleep(5)
    print('Morning comes, and your friends come out of their spots. They had fallen asleep waiting for your signal.')
    sleep(3)
    print()
    print('They both scream at the sight of your mangled corpse.')
    sleep(2)
    print()
    print('The police arrived and sent your friends back to the airport to go home. Your murder was not solved.')
    print()
    print('Ending 1 of X; "Oldest Trick in the Book"')
